### PR TITLE
Add function for AQL Table Creation

### PR DESCRIPTION
**Pull request by AlmightyYakob**

### CODE REVIEW

**Comment by AlmightyYakob** [comment]
> Looks good. Is there a way to test this, etc.?

Are you saying I should add tests to this method? Or are you asking about testing the functionality yourself?

Regarding the former, I agree, and can add them if we think it's a blocker. 
Regarding the latter, you would likely have to hook this up to your local Multinet client instance.

**Comment by waxlamp** [comment]
> > Looks good. Is there a way to test this, etc.?
> 
> Are you saying I should add tests to this method? Or are you asking about testing the functionality yourself?
> 
> Regarding the former, I agree, and can add them if we think it's a blocker.
> Regarding the latter, you would likely have to hook this up to your local Multinet client instance.

Sorry, I wasn't very clear about this.

I was asking more about the former. I guess the answer is something I could have figured out if I thought about it: now that we have a testing server, we can easily write a test case that uses this new function to make a table, then dump the table, make sure it has the right contents, and then remove the table, etc.

I would like you to add a test like that before merging, if I am right that it would be straightforward. I will dismiss my own review and make note of that, and you can let me know if it's feasible here.

**Comment by AlmightyYakob** [comment]
> I would like you to add a test like that before merging, if I am right that it would be straightforward. I will dismiss my own review and make note of that, and you can let me know if it's feasible here.

I agree it should be added, however currently we don't run the tests in CI, and before we do (since some of those involve creating/modifying workspaces) I think we should overhaul our testing strategy. Currently, it's basically a flat list of tests in one file, without any comments. I think it's necessary to convert this to something like Jest, with clearly defined test cases, and explicit creation/tear-down logic, in order to leave the testing database in a good state. If you agree with this, I can make an issue for it, and include that this test case should be added.

**Comment by waxlamp** [comment]
> > I would like you to add a test like that before merging, if I am right that it would be straightforward. I will dismiss my own review and make note of that, and you can let me know if it's feasible here.
> 
> I agree it should be added, however currently we don't run the tests in CI, and before we do (since some of those involve creating/modifying workspaces) I think we should overhaul our testing strategy. Currently, it's basically a flat list of tests in one file, without any comments. I think it's necessary to convert this to something like Jest, with clearly defined test cases, and explicit creation/tear-down logic, in order to leave the testing database in a good state. If you agree with this, I can make an issue for it, and include that this test case should be added.

Agreed. Please file that issue and assign @mvandenburgh (this would be a good spin-up task for him, and I'll discuss it with him when we meet later today).

**Pull request merged**
